<div class="span7">
    <style>
        td {
            border: thin solid gray;
        }
        th {
            color: green;
            border: thin solid gray;
        }
    </style>
    <h2><?= $this->escapeHtml(ucwords($this->category)); ?></h2>
    <?php if ($this->listing && $item = $this->listing->current()) : ?>
        <table width="100%" cellspacing="5px" cellpadding="5px">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Price</th>
                    <th>Posted</th>
                    <th>Expires</th>
                    <th>City</th>
                    <th>Country</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($item) : ?>
                <tr style="background-color:<?php echo $this->cycle(array('#F0F0F0', '#FFFFFF'))->next(); ?>;">
                    <td>
                        <a href="<?= $this->basePath(); ?>/market/view/item/<?= (int) $item->listings_id; ?>">
                            <b>
                                <i><?= $this->escapeHtml($item->title); ?></i>
                            </b>
                        </a>
                    </td>
                    <td>$<?= number_format($item->price,2); ?></td>
                    <td><?= $this->escapeHtml($item->date_created); ?></td>
                    <td><?= $this->escapeHtml($item->date_expires); ?></td>
                    <td><?= $this->escapeHtml($item->city); ?></td>
                    <td><?= $this->escapeHtml($item->country); ?></td>
                </tr>
                <?php $this->listing->next(); ?>
                <?php $item = $this->listing->current(); ?>
                <?php endwhile; ?>
            </tbody>
        </table>
    <?php else : ?>
        No Listings!
    <?php endif; ?>
</div>
